# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_of', to='pet.Pet'),
        ),
        migrations.AlterField(
            model_name='birth',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_of', to='pet.Pet'),
        ),
    ]
